window.esdocSearchIndex = [
  [
    "jser-stat/src/algo/algoitem.js~algoitem",
    "class/src/algo/AlgoItem.js~AlgoItem.html",
    "<span>AlgoItem</span> <span class=\"search-result-import-path\">jser-stat/src/algo/AlgoItem.js</span>",
    "class"
  ],
  [
    "jser-stat/src/algo/algopost.js~algopost",
    "class/src/algo/AlgoPost.js~AlgoPost.html",
    "<span>AlgoPost</span> <span class=\"search-result-import-path\">jser-stat/src/algo/AlgoPost.js</span>",
    "class"
  ],
  [
    "jser-stat/src/models/jseritem.js~jseritem",
    "class/src/models/JSerItem.js~JSerItem.html",
    "<span>JSerItem</span> <span class=\"search-result-import-path\">jser-stat/src/models/JSerItem.js</span>",
    "class"
  ],
  [
    "jser-stat/src/models/jseritemrelatedlink.js~jseritemrelatedlink",
    "class/src/models/JSerItemRelatedLink.js~JSerItemRelatedLink.html",
    "<span>JSerItemRelatedLink</span> <span class=\"search-result-import-path\">jser-stat/src/models/JSerItemRelatedLink.js</span>",
    "class"
  ],
  [
    "jser-stat/src/models/jserpost.js~jserpost",
    "class/src/models/JSerPost.js~JSerPost.html",
    "<span>JSerPost</span> <span class=\"search-result-import-path\">jser-stat/src/models/JSerPost.js</span>",
    "class"
  ],
  [
    "jser-stat/src/jserstat.js~jserstat",
    "class/src/JSerStat.js~JSerStat.html",
    "<span>JSerStat</span> <span class=\"search-result-import-path\">jser-stat/src/JSerStat.js</span>",
    "class"
  ],
  [
    "jser-stat/src/models/jserweek.js~jserweek",
    "class/src/models/JSerWeek.js~JSerWeek.html",
    "<span>JSerWeek</span> <span class=\"search-result-import-path\">jser-stat/src/models/JSerWeek.js</span>",
    "class"
  ],
  [
    "jser-stat/src/compute/compute-tags.js~countbygroup",
    "function/index.html#static-function-countByGroup",
    "<span>countByGroup</span> <span class=\"search-result-import-path\">jser-stat/src/compute/compute-tags.js</span>",
    "function"
  ],
  [
    "jser-stat/src/compute/compute-tags.js~counttagsbygroup",
    "function/index.html#static-function-countTagsByGroup",
    "<span>countTagsByGroup</span> <span class=\"search-result-import-path\">jser-stat/src/compute/compute-tags.js</span>",
    "function"
  ],
  [
    "jser-stat/src/algo/algosearch.js~findindexbiggertime",
    "function/index.html#static-function-findIndexBiggerTime",
    "<span>findIndexBiggerTime</span> <span class=\"search-result-import-path\">jser-stat/src/algo/algoSearch.js</span>",
    "function"
  ],
  [
    "jser-stat/src/algo/algosearch.js~findindexlesstime",
    "function/index.html#static-function-findIndexLessTime",
    "<span>findIndexLessTime</span> <span class=\"search-result-import-path\">jser-stat/src/algo/algoSearch.js</span>",
    "function"
  ],
  [
    "jser-stat/src/algo/algosearch.js~findindexesbetween",
    "function/index.html#static-function-findIndexesBetween",
    "<span>findIndexesBetween</span> <span class=\"search-result-import-path\">jser-stat/src/algo/algoSearch.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/jserstat.js",
    "file/src/JSerStat.js.html",
    "src/JSerStat.js",
    "file"
  ],
  [
    "src/jserstat.js~jserstat#algoitem",
    "class/src/JSerStat.js~JSerStat.html#instance-member-algoItem",
    "src/JSerStat.js~JSerStat#algoItem",
    "member"
  ],
  [
    "src/jserstat.js~jserstat#constructor",
    "class/src/JSerStat.js~JSerStat.html#instance-constructor-constructor",
    "src/JSerStat.js~JSerStat#constructor",
    "method"
  ],
  [
    "src/jserstat.js~jserstat#getitemsbetween",
    "class/src/JSerStat.js~JSerStat.html#instance-method-getItemsBetWeen",
    "src/JSerStat.js~JSerStat#getItemsBetWeen",
    "method"
  ],
  [
    "src/jserstat.js~jserstat#getjserweek",
    "class/src/JSerStat.js~JSerStat.html#instance-method-getJSerWeek",
    "src/JSerStat.js~JSerStat#getJSerWeek",
    "method"
  ],
  [
    "src/jserstat.js~jserstat#getjserweeks",
    "class/src/JSerStat.js~JSerStat.html#instance-method-getJSerWeeks",
    "src/JSerStat.js~JSerStat#getJSerWeeks",
    "method"
  ],
  [
    "src/jserstat.js~jserstat#getjserweeksbetween",
    "class/src/JSerStat.js~JSerStat.html#instance-method-getJSerWeeksBetWeen",
    "src/JSerStat.js~JSerStat#getJSerWeeksBetWeen",
    "method"
  ],
  [
    "src/jserstat.js~jserstat#gettotalweekcount",
    "class/src/JSerStat.js~JSerStat.html#instance-method-getTotalWeekCount",
    "src/JSerStat.js~JSerStat#getTotalWeekCount",
    "method"
  ],
  [
    "src/jserstat.js~jserstat#items",
    "class/src/JSerStat.js~JSerStat.html#instance-member-items",
    "src/JSerStat.js~JSerStat#items",
    "member"
  ],
  [
    "src/jserstat.js~jserstat#posts",
    "class/src/JSerStat.js~JSerStat.html#instance-member-posts",
    "src/JSerStat.js~JSerStat#posts",
    "member"
  ],
  [
    "src/algo/algoitem.js",
    "file/src/algo/AlgoItem.js.html",
    "src/algo/AlgoItem.js",
    "file"
  ],
  [
    "src/algo/algoitem.js~algoitem#constructor",
    "class/src/algo/AlgoItem.js~AlgoItem.html#instance-constructor-constructor",
    "src/algo/AlgoItem.js~AlgoItem#constructor",
    "method"
  ],
  [
    "src/algo/algoitem.js~algoitem#finditemsbetween",
    "class/src/algo/AlgoItem.js~AlgoItem.html#instance-method-findItemsBetween",
    "src/algo/AlgoItem.js~AlgoItem#findItemsBetween",
    "method"
  ],
  [
    "src/algo/algoitem.js~algoitem#itemtimes",
    "class/src/algo/AlgoItem.js~AlgoItem.html#instance-member-itemTimes",
    "src/algo/AlgoItem.js~AlgoItem#itemTimes",
    "member"
  ],
  [
    "src/algo/algoitem.js~algoitem#items",
    "class/src/algo/AlgoItem.js~AlgoItem.html#instance-member-items",
    "src/algo/AlgoItem.js~AlgoItem#items",
    "member"
  ],
  [
    "src/algo/algopost.js",
    "file/src/algo/AlgoPost.js.html",
    "src/algo/AlgoPost.js",
    "file"
  ],
  [
    "src/algo/algopost.js~algopost#constructor",
    "class/src/algo/AlgoPost.js~AlgoPost.html#instance-constructor-constructor",
    "src/algo/AlgoPost.js~AlgoPost#constructor",
    "method"
  ],
  [
    "src/algo/algopost.js~algopost#findpostsbetween",
    "class/src/algo/AlgoPost.js~AlgoPost.html#instance-method-findPostsBetween",
    "src/algo/AlgoPost.js~AlgoPost#findPostsBetween",
    "method"
  ],
  [
    "src/algo/algopost.js~algopost#posttimeindex",
    "class/src/algo/AlgoPost.js~AlgoPost.html#instance-member-postTimeIndex",
    "src/algo/AlgoPost.js~AlgoPost#postTimeIndex",
    "member"
  ],
  [
    "src/algo/algopost.js~algopost#posts",
    "class/src/algo/AlgoPost.js~AlgoPost.html#instance-member-posts",
    "src/algo/AlgoPost.js~AlgoPost#posts",
    "member"
  ],
  [
    "src/algo/algosearch.js",
    "file/src/algo/algoSearch.js.html",
    "src/algo/algoSearch.js",
    "file"
  ],
  [
    "src/compute/compute-tags.js",
    "file/src/compute/compute-tags.js.html",
    "src/compute/compute-tags.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/models/jseritem.js",
    "file/src/models/JSerItem.js.html",
    "src/models/JSerItem.js",
    "file"
  ],
  [
    "src/models/jseritem.js~jseritem#constructor",
    "class/src/models/JSerItem.js~JSerItem.html#instance-constructor-constructor",
    "src/models/JSerItem.js~JSerItem#constructor",
    "method"
  ],
  [
    "src/models/jseritem.js~jseritem#content",
    "class/src/models/JSerItem.js~JSerItem.html#instance-member-content",
    "src/models/JSerItem.js~JSerItem#content",
    "member"
  ],
  [
    "src/models/jseritem.js~jseritem#date",
    "class/src/models/JSerItem.js~JSerItem.html#instance-member-date",
    "src/models/JSerItem.js~JSerItem#date",
    "member"
  ],
  [
    "src/models/jseritem.js~jseritem#relatedlinks",
    "class/src/models/JSerItem.js~JSerItem.html#instance-member-relatedLinks",
    "src/models/JSerItem.js~JSerItem#relatedLinks",
    "member"
  ],
  [
    "src/models/jseritem.js~jseritem#tags",
    "class/src/models/JSerItem.js~JSerItem.html#instance-member-tags",
    "src/models/JSerItem.js~JSerItem#tags",
    "member"
  ],
  [
    "src/models/jseritem.js~jseritem#title",
    "class/src/models/JSerItem.js~JSerItem.html#instance-member-title",
    "src/models/JSerItem.js~JSerItem#title",
    "member"
  ],
  [
    "src/models/jseritem.js~jseritem#url",
    "class/src/models/JSerItem.js~JSerItem.html#instance-member-url",
    "src/models/JSerItem.js~JSerItem#url",
    "member"
  ],
  [
    "src/models/jseritemrelatedlink.js",
    "file/src/models/JSerItemRelatedLink.js.html",
    "src/models/JSerItemRelatedLink.js",
    "file"
  ],
  [
    "src/models/jseritemrelatedlink.js~jseritemrelatedlink#constructor",
    "class/src/models/JSerItemRelatedLink.js~JSerItemRelatedLink.html#instance-constructor-constructor",
    "src/models/JSerItemRelatedLink.js~JSerItemRelatedLink#constructor",
    "method"
  ],
  [
    "src/models/jseritemrelatedlink.js~jseritemrelatedlink#title",
    "class/src/models/JSerItemRelatedLink.js~JSerItemRelatedLink.html#instance-member-title",
    "src/models/JSerItemRelatedLink.js~JSerItemRelatedLink#title",
    "member"
  ],
  [
    "src/models/jseritemrelatedlink.js~jseritemrelatedlink#url",
    "class/src/models/JSerItemRelatedLink.js~JSerItemRelatedLink.html#instance-member-url",
    "src/models/JSerItemRelatedLink.js~JSerItemRelatedLink#url",
    "member"
  ],
  [
    "src/models/jserpost.js",
    "file/src/models/JSerPost.js.html",
    "src/models/JSerPost.js",
    "file"
  ],
  [
    "src/models/jserpost.js~jserpost#category",
    "class/src/models/JSerPost.js~JSerPost.html#instance-member-category",
    "src/models/JSerPost.js~JSerPost#category",
    "member"
  ],
  [
    "src/models/jserpost.js~jserpost#constructor",
    "class/src/models/JSerPost.js~JSerPost.html#instance-constructor-constructor",
    "src/models/JSerPost.js~JSerPost#constructor",
    "method"
  ],
  [
    "src/models/jserpost.js~jserpost#content",
    "class/src/models/JSerPost.js~JSerPost.html#instance-member-content",
    "src/models/JSerPost.js~JSerPost#content",
    "member"
  ],
  [
    "src/models/jserpost.js~jserpost#date",
    "class/src/models/JSerPost.js~JSerPost.html#instance-member-date",
    "src/models/JSerPost.js~JSerPost#date",
    "member"
  ],
  [
    "src/models/jserpost.js~jserpost#postnumber",
    "class/src/models/JSerPost.js~JSerPost.html#instance-member-postNumber",
    "src/models/JSerPost.js~JSerPost#postNumber",
    "member"
  ],
  [
    "src/models/jserpost.js~jserpost#tags",
    "class/src/models/JSerPost.js~JSerPost.html#instance-member-tags",
    "src/models/JSerPost.js~JSerPost#tags",
    "member"
  ],
  [
    "src/models/jserpost.js~jserpost#title",
    "class/src/models/JSerPost.js~JSerPost.html#instance-member-title",
    "src/models/JSerPost.js~JSerPost#title",
    "member"
  ],
  [
    "src/models/jserpost.js~jserpost#url",
    "class/src/models/JSerPost.js~JSerPost.html#instance-member-url",
    "src/models/JSerPost.js~JSerPost#url",
    "member"
  ],
  [
    "src/models/jserweek.js",
    "file/src/models/JSerWeek.js.html",
    "src/models/JSerWeek.js",
    "file"
  ],
  [
    "src/models/jserweek.js~jserweek#begindate",
    "class/src/models/JSerWeek.js~JSerWeek.html#instance-member-beginDate",
    "src/models/JSerWeek.js~JSerWeek#beginDate",
    "member"
  ],
  [
    "src/models/jserweek.js~jserweek#constructor",
    "class/src/models/JSerWeek.js~JSerWeek.html#instance-constructor-constructor",
    "src/models/JSerWeek.js~JSerWeek#constructor",
    "method"
  ],
  [
    "src/models/jserweek.js~jserweek#enddate",
    "class/src/models/JSerWeek.js~JSerWeek.html#instance-member-endDate",
    "src/models/JSerWeek.js~JSerWeek#endDate",
    "member"
  ],
  [
    "src/models/jserweek.js~jserweek#items",
    "class/src/models/JSerWeek.js~JSerWeek.html#instance-member-items",
    "src/models/JSerWeek.js~JSerWeek#items",
    "member"
  ],
  [
    "src/models/jserweek.js~jserweek#post",
    "class/src/models/JSerWeek.js~JSerWeek.html#instance-member-post",
    "src/models/JSerWeek.js~JSerWeek#post",
    "member"
  ],
  [
    "src/models/jserweek.js~jserweek#weeknumber",
    "class/src/models/JSerWeek.js~JSerWeek.html#instance-member-weekNumber",
    "src/models/JSerWeek.js~JSerWeek#weekNumber",
    "member"
  ]
]